### PR TITLE
Updated TenantId input and variables

### PR DESCRIPTION
**Pull request by jayanthsagar**
Purge-AzureCDNEndpoint.ps1 was missing TenantId and SubscriptionId variables declaration. I have added that and updated task.json with input for TenantId

### CODE REVIEW

**Comment by FabienLavocat** [comment]
Thanks @jayanthsagar for your pull request!
Here is the stack of the error you were having when using the task on Azure DevOps.

```
Leaving Initialize-Azure.
2018-10-25T10:39:42.0250184Z ##[debug]Leaving H:\vsts6\_work\_tasks\PurgeAzureCDNEndpoint_80099f87-0d5a-4834-a8eb-af17c841dad3\1.0.1\Purge-AzureCDNEndpoint.ps1.
2018-10-25T10:39:42.0320141Z ##[debug]Caught exception from task script.
2018-10-25T10:39:42.0365636Z ##[debug]Error record:
2018-10-25T10:39:42.1124015Z ##[debug]Select-AzureRMSubscription : Please provide a valid tenant or a valid subscription.
2018-10-25T10:39:42.1138979Z ##[debug]At H:\vsts6\_work\_tasks\PurgeAzureCDNEndpoint_80099f87-0d5a-4834-a8eb-af17c841dad3\1.0.1\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1:142 char:13
2018-10-25T10:39:42.1153105Z ##[debug]+     $null = Select-AzureRMSubscription -SubscriptionId $SubscriptionI ...
2018-10-25T10:39:42.1167662Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-10-25T10:39:42.1181522Z ##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
2018-10-25T10:39:42.1195584Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
2018-10-25T10:39:42.1209904Z ##[debug] 
2018-10-25T10:39:42.1563757Z ##[debug]Script stack trace:
```

Have you selected the Subscription properly in the definition of your pipeline? There is a field called "Azure Subscription". I'm asking because if you select a subscription in this section, you shouldn't need any extra parameters (Subscription ID and Tenant ID)

**Comment by jayanthsagar** [comment]
ya, I have selected Subscriptioncorrectly, I ran the InitializeFunctions.ps1 alone and its the same issue

**Comment by FabienLavocat** [comment]
One possibility is the way you have created the connection to the Azure subscription in your DevOps account. Have you created it using the "Service Principal"?
In Azure DevOps, go to your _Service connections_ and select the Azure Subscription you want to use in your pipeline. Do you have a message that says: "Connecting to service using Service Principal"

**Comment by jayanthsagar** [comment]
Just figured out, it was a delay from Microsoft side getting tenantId from the connection , I am facing the same kind of error in other tasks also. But yeah, giving the tenantID in the task as input is good enough as long as the tenantId is not changed.

**Comment by FabienLavocat** [comment]
If it was a problem on the Microsoft side, I'd rather have them fix it. Adding the TenantID might be confusing.

**Pull request closed without merging**
